db:
  type: sqlite
  path: '/tmp/upgradehub'

scan:
  #zk sync diamond proxy address
  address: '0x32400084c286cf3e17e7b677ea9583e60a000324'
  network: 'etherscan'

file:
  temp_path: '/tmp/upgradehub'

app:
  port: 3000